#pragma once

#include <stddef.h>  // size_t
#include <stdint.h>  // uint*_t

#include "../bcs/types.h"

typedef enum {
    PARSING_OK = 1,
    HASHED_PREFIX_READ_ERROR = -1,
    SENDER_READ_ERROR = -2,
    SEQUENCE_READ_ERROR = -3,
    MAX_GAS_READ_ERROR = -4,
    GAS_UNIT_PRICE_READ_ERROR = -5,
    EXPIRATION_READ_ERROR = -6,
    CHAIN_ID_READ_ERROR = -7,
    PAYLOAD_VARIANT_READ_ERROR = -8,
    PAYLOAD_UNDEFINED_ERROR = -9,
    MODULE_ID_ADDR_READ_ERROR = -10,
    MODULE_ID_NAME_LEN_READ_ERROR = -11,
    MODULE_ID_NAME_BYTES_READ_ERROR = -12,
    FUNCTION_NAME_LEN_READ_ERROR = -13,
    FUNCTION_NAME_BYTES_READ_ERROR = -14,
    TYPE_ARGS_SIZE_READ_ERROR = -15,
    TYPE_ARGS_SIZE_UNEXPECTED_ERROR = -16,
    ARGS_SIZE_READ_ERROR = -17,
    ARGS_SIZE_UNEXPECTED_ERROR = -18,
    RECEIVER_ADDR_LEN_READ_ERROR = -19,
    WRONG_ADDRESS_LEN_ERROR = -20,
    RECEIVER_ADDR_READ_ERROR = -21,
    AMOUNT_LEN_READ_ERROR = -22,
    WRONG_AMOUNT_LEN_ERROR = -23,
    AMOUNT_READ_ERROR = -24,
    TYPE_TAG_READ_ERROR = -25,
    TYPE_TAG_UNEXPECTED_ERROR = -26,
    STRUCT_ADDRESS_READ_ERROR = -27,
    STRUCT_MODULE_LEN_READ_ERROR = -28,
    STRUCT_MODULE_BYTES_READ_ERROR = -29,
    STRUCT_NAME_LEN_READ_ERROR = -30,
    STRUCT_NAME_BYTES_READ_ERROR = -31,
    STRUCT_TYPE_ARGS_SIZE_READ_ERROR = -32,
    STRUCT_TYPE_ARGS_SIZE_UNEXPECTED_ERROR = -33,
    TX_VARIANT_READ_ERROR = -34,
    TX_VARIANT_UNDEFINED_ERROR = -35,
    WRONG_LENGTH_ERROR = -2000
} parser_status_e;

typedef aptos_transaction_t transaction_t;
